# Generated by Django 3.2.18 on 2023-05-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20230514_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interno',
            old_name='baja',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='baja',
            new_name='estado',
        ),
    ]
